class EventTypes:
    WORKER_STARTED = "Worker.Started"
    WORKER_COMPLETED = "Worker.Completed"
    WORKER_FAILED = "Worker.Failed"
    HEALTH_COLLECTED = "System.HealthCollected"
    HIGH_CPU = "System.HighCPU"
    HIGH_RAM = "System.HighRAM"
    HIGH_SWAP = "System.HighSwap"
    HIGH_DISK = "System.HighDisk"
    DOCKER_COLLECTED = "Docker.Collected"
    CONTAINER_STOPPED = "Docker.ContainerStopped"
    CONTAINER_STARTED = "Docker.ContainerStarted"
    CONTAINER_UNKNOWN = "Docker.ContainerUnknown"
    RECOMMENDATION_CREATED = "Recommendation.Created"
    RECOMMENDATION_DISMISSED = "Recommendation.Dismissed"
